name: First GitHub Action

on:
  pull_request:
    branches:
      - service-layer
     

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "🎉 Hello from GitHub Actions!"
